services:

  broker:
    build:
      context: ./src/broker
      dockerfile: Dockerfile_broker
    container_name: broker
    ports:
      - 5555:5555
      - 5556:5556

  proxy:
    build:
      context: ./src/proxy
      dockerfile: Dockerfile_proxy
    container_name: proxy
    ports:
      - "5557:5557"   # XSUB
      - "5558:5558"   # XPUB

  servidor:
    build:
      context: ./src/servidor
      dockerfile: Dockerfile_servidor
    depends_on:
      - broker
      # - proxy
    volumes:
      - ./data:/app/data

  cliente:
    build:
      context: ./src/cliente
      dockerfile: Dockerfile_cliente
    depends_on:
      - servidor
    stdin_open: true   # <= mantÃ©m STDIN aberto
    tty: true          # <= aloca um TTY
